default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.28.0

images:
  - docker.io/elastic/rally:2.10.0
 # - docker.io/quay.io/jacksontj/promxy
 # - jimmidyson/configmap-reload:v0.1
