default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.28.0

images:
  - docker.io/library/mysql:5.7.34
 # - docker.io/quay.io/jacksontj/promxy
 # - jimmidyson/configmap-reload:v0.1
