default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.28.0

images:
  - docker.io/library/postgres:9.6.15
 # - docker.io/quay.io/jacksontj/promxy
 # - jimmidyson/configmap-reload:v0.1
