default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.28.0

images:
  - docker.io/apache/skywalking-ui:10.1.0
  - docker.io/apache/skywalking-oap-server:10.1.0
  - docker.io/library/elasticsearch:7.17.25
