default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.28.0

images:
  - registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20231011-8b53cabe0@sha256:a7943503b45d552785aa3b5e457f169a5661fb94d82b8a3373bcd9ebaf9aac80
