default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.28.0

images:
  - docker.io/minio/minio:RELEASE.2023-03-20T20-16-18Z
  - docker.io/milvusdb/etcd:3.5.16-r1
  - docker.io/apachepulsar/pulsar:3.0.7
