default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.28.0

images:
  - docker.io/spinnakercd/argocd-blue-green:v1
  - docker.io/spinnakercd/argocd-blue-green:v2
  - docker.io/spinnakercd/argocd-blue-green:v3
