default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.28.0

images:
  - registry.k8s.io/defaultbackend-amd64:1.5
  - registry.k8s.io/ingress-nginx/controller:v1.9.4
  - registry.k8s.io/ingress-nginx/opentelemetry:v20230721-3e2062ee5
