default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.28.0

images:
  - docker.io/centos:centos7.9.2009
 # - docker.io/quay.io/jacksontj/promxy
 # - jimmidyson/configmap-reload:v0.1
