default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.28.0

images:
  - docker.io/grafana/grafana:10.1.5
  - ghcr.io/prometheus-operator/prometheus-config-reloader:v0.67.0
  - docker.io/prom/prometheus:v2.48.0
